### ISSUE TITLE
[Request] Update README with onboarding instructions

### ISSUE THREAD

**Issue by evancharlton** [jossi87/climbing-ws#2]
I would love to get a local server stood up, even if it's just pointing at an empty MySQL server. Could you add some instructions for how to do that? I have it imported into Eclipse (I'm guessing that's the IDE you use), but I'm not sure what to from there.

(Specifically, I'm hoping to poke at the Swagger setup a bit more, but I imagine I'll outgrow that some day)

**Comment by jossi87** [comment]
Good idea, I'll write this on my todo-block. I'll look into it at soon as I can!

**Comment by evancharlton** [comment]
This is great, thank you! I (finally) went through it recently and noted some deficiencies:

1. **Tests don't work against the initial database.**
  The tests assume all kinds of data which doesn't exist in the data-free data dump.
2. **Tests run against an actual database.**
  I think it would be worthwhile to set up an in-memory DBC, like [MariaDB4j](https://github.com/MariaDB4j/MariaDB4j). (That's just a random example from Google; there are other options of course)

**Comment by jossi87** [comment]
Thanks for the update.

1. Noted, I guess the solution here is to add dummy data in init.sql.
2. I have no experience with in-memory DBC's. So I am not able to comment on this one 🙂
3. Did not think about this one, I added the function and some description directly in you PR, we can resolve this point there.

**Comment by evancharlton** [comment]
1. There are a few approaches I can think of - but this isn't really blocking me (all I did was just replace `@Test` with `// @Test`).
2. It doesn't have to be in-memory specifically. It could be that the lowest-friction approach in the short term is to create a `buldreinfo_testing` database for the unit tests and then run tests against that instead. I'll play around and see how badly I can mess things up 😉 
3. Sounds great, thanks!
