### ISSUE TITLE
[bug?] Activity#media and Activity#users are never exposed

### ISSUE THREAD

**Issue by evancharlton** [jossi87/climbing-ws#3]
I don't know if this is a bug or an artifact of a previous refactoring, but it's odd: [the `Activity` class](https://github.com/jossi87/climbing-ws/blob/main/src/com/buldreinfo/jersey/jaxb/model/Activity.java) has a [`media` field] and a [`users` field]. However, these don't have any public getters. The result of this is that they don't get represented in the Swagger definition -- but maybe they wind up in the untyped JSON? I'm not totally sure how to verify this theory.

[`media` field]:
  https://github.com/jossi87/climbing-ws/blob/main/src/com/buldreinfo/jersey/jaxb/model/Activity.java#L71
[`users` field]:
  https://github.com/jossi87/climbing-ws/blob/main/src/com/buldreinfo/jersey/jaxb/model/Activity.java#L79

**Comment by evancharlton** [comment]
Secondary observation: I believe that this makes `ActivityMedia` and `ActivityUser` also disappear from the generated swagger spec.

**Comment by jossi87** [comment]
Yeah, you are correct. Swagger only includes data with getters, but the ws returns every object as json. This one is fixed now, just let me know if you find others missing.
